name: Build

on:
  pull_request:

jobs:
  get-files:
    name: Get Software List Files
    runs-on: ubuntu-latest
    outputs:
      paths: ${{ steps.get-files.outputs.paths }}
    steps:
      - name: Get Software List Files
        id: list-files
        uses: mirko-felice/list-files-action@v3.0.5
        with:
          repo: ${{ github.repository }}
          ref: ${{ github.ref }}
          path: "Lists/"
          ext: ".json"
  test-files:
    runs-on: ubuntu-latest
    name: Test Software List Files
    needs: get-files
    strategy:
      matrix:
        paths: ${{ fromJson(needs.get-files.outputs.paths) }}
    steps:
    - uses: actions/checkout@v4
    - name: Test Files
      run: go run ./fileverifier/main.go -filepath ${{ matrix.paths }}

  build-desktop:
    needs: 
    - test-files
    name: Desktop App
    runs-on: ubuntu-latest
    env:
      NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
        cache: true
        cache-dependency-path: 'CSAUSBTool.CrossPlatform.Desktop/packages.lock.json'
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore CSAUSBTool.CrossPlatform.Desktop/CSAUSBTool.CrossPlatform.Desktop.csproj
